name: CI
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  USE_HARD_LINKS: false
 
jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: self-hosted
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Setup Node.js environment
          uses: pnpm/action-setup@v2
          with:
            version: 8
 
        - name: Install dependencies
          run: pnpm install
 
        - name: Lint
          run: pnpm lint

        - name: Typecheck
          run: pnpm typecheck

        - name: Build
          run: pnpm build
 
        - name: Compile
          run: pnpm compile

        - name: Removed unpacked release
          run: rm -rf apps/frontend/dist/linux-unpacked

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.0
          with:
    # Artifact name
            name: Linux build# optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
            path: apps/frontend/dist
